version: "2"
services:
  mysql:
    image: mariadb
    container_name: db
    
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shift
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
  app:
    image: 9560908608/doceree_test:v1
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - mysql
    environment:
      DB_DATABASE: shift
      DB_HOST: db
      DB_USERNAME: user
      DB_PASSWORD: password
      APP_DEBUG: 'true'
      APP_KEY: ibXjzma17W6BhqYjGcrtYjx4UT2pXTih
    command: bash -c "sleep 600s && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=8000"
  
  frontend:
    image: 9560908608/doceree_test_frontend:v1
    ports:
      - 3000:3000
    depends_on:
      - app
